name = "cf-workers-hono-fauna-app"
main = 'dist/index.js'

workers_dev = true
compatibility_date = '2022-05-05'
account_id=''

[miniflare]
kv_persist = false
env_path = '.env.test'

[vars]
ENV = 'development'
JWT_ACCESS_EXPIRATION_MINUTES=30
JWT_REFRESH_EXPIRATION_DAYS=30
JWT_RESET_PASSWORD_EXPIRATION_MINUTES=15
JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=15

[build]
command = "npm run build"

# [secrets]
# MYSQL_URL
# JWT_SECRET
